apiVersion: v1
kind: Pod
metadata:
  name: build-image
spec:
  containers:
  - name: mypod
    image: centos:centos7
    resources:
      limits:
        memory: 4Gi
        cpu: 1
      requests:
        memory: 4Gi
        cpu: 1
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - name: hm-storage
        mountPath: /data
  volumes:
    - name: hm-storage
      persistentVolumeClaim:
          claimName: hm-storage